### ISSUE TITLE
Lots of warnings in Log from Jenkins CodePipeline plugin

### ISSUE THREAD

**Issue by jlouis** [awslabs/aws-codepipeline-plugin-for-jenkins#13] opened 2016-08-08 12:38 UTC
Hi!

We have lots of these warnings in our jenkins debug log output. They started some weeks ago and I believe they eventually makes Jenkins leak until it hits an Out of Memory situation. I've been looking at the heap and it seems like it has numerous credentials from SSL on it. The plugin version is 0.16, but I'm fairly sure 0.15 also has the bug. I've seen you've made several changes to the SSL part, so this is a heads up and a question on how to proceed?

The Jenkins version is the newest possible (2.17) and the VM is 1.8.0_101/Oracle. Machine is an Ubuntu 14.04, running on AWS EC2.

I have a heap-dump before things goes really bad, where the main problem in that heap-dump is a large hash array where every element it contains a x509 credentials, and other SSL data. It would seem they get allocated by never cleared again, but I don't know how to get any closer to this problem.

An example of a warning before things goes awry is the following:

```
Aug 05, 2016 8:11:47 AM com.amazonaws.http.AmazonHttpClient executeHelper
INFO: Unable to execute HTTP request: Remote host closed connection during handshake
javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:992)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
        at com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.connectSocket(SdkTLSSocketFactory.java:131)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
        at sun.reflect.GeneratedMethodAccessor67.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
        at com.amazonaws.http.conn.$Proxy53.connect(Unknown Source)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
        at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:787)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:630)
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:405)
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:367)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:318)
        at com.amazonaws.services.codepipeline.AWSCodePipelineClient.doInvoke(AWSCodePipelineClient.java:1842)
        at com.amazonaws.services.codepipeline.AWSCodePipelineClient.invoke(AWSCodePipelineClient.java:1812)
        at com.amazonaws.services.codepipeline.AWSCodePipelineClient.pollForJobs(AWSCodePipelineClient.java:1298)
        at com.amazonaws.codepipeline.jenkinsplugin.AWSCodePipelineSCM.pollForJobs(AWSCodePipelineSCM.java:229)
        at com.amazonaws.codepipeline.jenkinsplugin.AWSCodePipelineSCM.compareRemoteRevisionWith(AWSCodePipelineSCM.java:171)
        at hudson.scm.SCM.poll(SCM.java:408)
        at hudson.model.AbstractProject._poll(AbstractProject.java:1460)
        at hudson.model.AbstractProject.poll(AbstractProject.java:1363)
        at hudson.triggers.SCMTrigger$Runner.runPolling(SCMTrigger.java:528)
        at hudson.triggers.SCMTrigger$Runner.run(SCMTrigger.java:574)
        at hudson.util.SequentialExecutionQueue$QueueEntry.run(SequentialExecutionQueue.java:119)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at sun.security.ssl.InputRecord.read(InputRecord.java:505)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
        ... 41 more
```

And the last one before it crashes is the following:

```
Aug 05, 2016 9:14:09 AM com.amazonaws.http.AmazonHttpClient executeHelper
INFO: Unable to execute HTTP request: Remote host closed connection during handshake
javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:992)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
        at com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.connectSocket(SdkTLSSocketFactory.java:131)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
        at sun.reflect.GeneratedMethodAccessor67.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
        at com.amazonaws.http.conn.$Proxy53.connect(Unknown Source)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
        at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:787)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:630)
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:405)
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:367)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:318)
        at com.amazonaws.services.codepipeline.AWSCodePipelineClient.doInvoke(AWSCodePipelineClient.java:1842)
        at com.amazonaws.services.codepipeline.AWSCodePipelineClient.invoke(AWSCodePipelineClient.java:1812)
        at com.amazonaws.services.codepipeline.AWSCodePipelineClient.pollForJobs(AWSCodePipelineClient.java:1298)
        at com.amazonaws.codepipeline.jenkinsplugin.AWSCodePipelineSCM.pollForJobs(AWSCodePipelineSCM.java:229)
        at com.amazonaws.codepipeline.jenkinsplugin.AWSCodePipelineSCM.compareRemoteRevisionWith(AWSCodePipelineSCM.java:171)
        at hudson.scm.SCM.poll(SCM.java:408)
        at hudson.model.AbstractProject._poll(AbstractProject.java:1460)
        at hudson.model.AbstractProject.poll(AbstractProject.java:1363)
        at hudson.triggers.SCMTrigger$Runner.runPolling(SCMTrigger.java:528)
        at hudson.triggers.SCMTrigger$Runner.run(SCMTrigger.java:574)
        at hudson.util.SequentialExecutionQueue$QueueEntry.run(SequentialExecutionQueue.java:119)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at sun.security.ssl.InputRecord.read(InputRecord.java:505)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
        ... 41 more
```

**Comment by jlouis** [comment] 2016-08-08 12:55
The thing which is filled up in our Jenkins instance's heap dump is "java.util.HashMap". A typical entry in the hashmap is a key such as `X509CertImpl`. About 32% of the heap space is taken up by these when the system runs out of memory. This is from a smaller heap dump. The full dump at 3.1 Gigabyte is available, but my VisualVM instance can't really handle it.

**Comment by biagic** [comment] 2016-08-08 22:19
Hi, thanks for bringing this to our attention.

I think this might be the root cause: https://github.com/aws/aws-sdk-java/issues/722
The issue was fixed in version 1.11.6, but our plugin still uses 1.11.3 (since version 0.14).

Let us run some tests to see if we can reproduce the issue, and test if upgrading the AWS Java SDK to the latest version (1.11.24) fixes the issue.

In the meantime, you could give it a try (and let us know how it goes) by:

* Checking out this repo.
* Bumping the aws-java-sdk version to 1.11.24 in `pom.xml`.
* Running maven `mvn`.
* Manually installing the SNAPSHOT version created in `target/aws-codepipeline.hpi`.

**Comment by jlouis** [comment] 2016-08-09 10:08
Thank you for the quick turnaround reply. I'll try what you suggest, and report back what happens.

**Comment by jlouis** [comment] 2016-08-10 11:14
Having run the suggested fix for one day, it looks like it has solved the problem. The memory usage is what is expected, and there don't seem to be any leak. Furthermore, the warnings in the log are gone. Normally, about 24 hours were enough to OOM our instance, but that doesn't happen anymore.

Patch follows:

```
tiefling:aws-codepipeline-plugin-for-jenkins jlouis$ git diff
diff --git i/pom.xml w/pom.xml
index 1f00613..acede62 100644
--- i/pom.xml
+++ w/pom.xml
@@ -63,7 +63,7 @@
     <dependency>
       <groupId>com.amazonaws</groupId>
       <artifactId>aws-java-sdk</artifactId>
-      <version>1.11.3</version>
+      <version>1.11.24</version>
     </dependency>
     <dependency>
       <groupId>org.apache.commons</groupId>
```

**Comment by biagic** [comment] 2016-08-10 18:10
Great, out testing looks good too, so we'll be releasing a new version of the plugin soon.

**Closed** 2016-08-11 00:45 UTC
